(* i dropped the commas cause theyre annoying :3 *)

expr = comparison;
comparison = term [ comparisonOperator term ];
term = factor { ( '+' | '-' ) factor };
factor = (unary | primary) { ( '*' | '/' | '%' ) (unary | primary) };
unary = ('!' | '-') primary;
primary = '(' expr ')' | primative;

comparisonOperator = '>' | '>=' | '<' | '<=' | '==' | '!=';
primative = NUMBER | STRING | CHARACTER | BOOL | NULL;